package com.wangdi.util.chemistry;

import java.util.HashMap;
import java.util.Map;

public final class ChemicalFormula
{
    //simple substance
    public static final String HYDROGEN = "H2";
    public static final String HELIUM = "He";
    public static final String LITHIUM = "Li";
    public static final String BERYLLIUM = "Be";
    public static final String BORON = "B";
    public static final String CARBON = "C";
    public static final String NITROGEN = "N2";
    public static final String OXYGEN = "O2";
    public static final String FLUORINE = "F2";
    public static final String NEON = "Ne";
    public static final String SODIUM = "Na";
    public static final String MAGNESIUM = "Mg";
    public static final String ALUMINIUM = "Al";
    public static final String SILICON = "Si";
    public static final String PHOSPHORUS = "P4";
    public static final String SULFUR = "S8";
    public static final String CHLORINE = "Cl2";
    public static final String ARGON = "Ar";
    public static final String POTASSIUM = "K";
    public static final String CALCIUM = "Ca";
    public static final String SCANDIUM = "Sc";
    public static final String TITANIUM = "Ti";
    public static final String VANADIUM = "V";
    public static final String CHROMIUM = "Cr";
    public static final String MANGANESE = "Mn";
    public static final String IRON = "Fe";
    public static final String COBALT = "Co";
    public static final String NICKEL = "Ni";
    public static final String COPPER = "Cu";
    public static final String ZINC = "Zn";
    public static final String GALLIUM = "Ga";
    public static final String GERMANIUM = "Ge";
    public static final String ARSENIC = "As4";
    public static final String SELENIUM = "Se";
    public static final String BROMINE = "Br2";
    public static final String KRYPTON = "Kr";
    public static final String RUBIDIUM = "Rb";
    public static final String STRONTIUM = "Sr";
    public static final String YTTRIUM = "Y";
    public static final String ZIRCONIUM = "Zr";
    public static final String NIOBIUM = "Nb";
    public static final String MOLYBDENUM = "Mo";
    public static final String TECHNETIUM = "Tc";
    public static final String RUTHENIUM = "Ru";
    public static final String RHODIUM = "Rh";
    public static final String PALLADIUM = "Pd";
    public static final String SILVER = "Ag";
    public static final String CADMIUM = "Cd";
    public static final String INDIUM = "In";
    public static final String TIN = "Sn";
    public static final String ANTIMONY = "Sb";
    public static final String TELLURIUM = "Te";
    public static final String IODINE = "I2";
    public static final String XENON = "Xe";
    public static final String CESIUM = "Cs";
    public static final String BARIUM = "Ba";
    public static final String LANTHANUM = "La";
    public static final String CERIUM = "Ce";
    public static final String PRASEODYMIUM = "Pr";
    public static final String NEODYMIUM = "Nd";
    public static final String PROMETHIUM = "Pm";
    public static final String SAMARIUM = "Sm";
    public static final String EUROPIUM = "Eu";
    public static final String GADOLINIUM = "Gd";
    public static final String TERBIUM = "Tb";
    public static final String DYSPROSIUM = "Dy";
    public static final String HOLMIUM = "Ho";
    public static final String ERBIUM = "Er";
    public static final String THULIUM = "Tm";
    public static final String YTTERBIUM = "Yb";
    public static final String LUTETIUM = "Lu";
    public static final String HAFNIUM = "Hf";
    public static final String TANTALUM = "Ta";
    public static final String TUNGSTEN = "W";
    public static final String RHENIUM = "Re";
    public static final String OSMIUM = "Os";
    public static final String IRIDIUM = "Ir";
    public static final String PLATINUM = "Pt";
    public static final String GOLD = "Au";
    public static final String MERCURY = "Hg";
    public static final String THALLIUM = "Tl";
    public static final String LEAD = "Pb";
    public static final String BISMUTH = "Bi";
    public static final String POLONIUM = "Po";
    public static final String ASTATINE = "At";
    public static final String RADON = "Rn";
    public static final String FRANCIUM = "Fr";
    public static final String RADIUM = "Ra";
    public static final String ACTINIUM = "Ac";
    public static final String THORIUM = "Th";
    public static final String PROTACTINIUM = "Pa";
    public static final String URANIUM = "U";
    public static final String NEPTUNIUM = "Np";
    public static final String PLUTONIUM = "Pu";
    public static final String AMERICIUM = "Am";
    public static final String CURIUM = "Cm";
    public static final String BERKELIUM = "Bk";
    public static final String CALIFORNIUM = "Cf";
    public static final String EINSTEINIUM = "Es";
    public static final String FERMIUM = "Fm";
    public static final String MENDELEVIUM = "Md";
    public static final String NOBELIUM = "No";
    public static final String LAWRENCIUM = "Lr";
    public static final String RUTHERFORDIUM = "Rf";
    public static final String DUBNIUM = "Db";
    public static final String SEABORGIUM = "Sg";
    public static final String BOHRIUM = "Bh";
    public static final String HASSIUM = "Hs";
    public static final String MEITNERIUM = "Mt";
    public static final String DARMSTADTIUM = "Ds";
    public static final String ROENTGENIUM = "Rg";
    public static final String COPERNICIUM = "Cn";
    public static final String NIHONIUM = "Nh";
    public static final String FLEROVIUM = "Fl";
    public static final String MOSCOVIUM = "Mc";
    public static final String LIVERMORIUM = "Lv";
    public static final String TENNESSINE = "Ts";
    public static final String OGANESSON = "Og";

    public static final String WATER = "H2O";

    private static final Map<String, String> NAME_TABLE = new HashMap<String, String>()
    {
        {   //simple substance
            this.put(HYDROGEN, "hydrogen");
            this.put(HELIUM, "helium");
            this.put(LITHIUM, "lithium");
            this.put(BERYLLIUM, "beryllium");
            this.put(BORON, "boron");
            this.put(CARBON, "carbon");
            this.put(NITROGEN, "nitrogen");
            this.put(OXYGEN, "oxygen");
            this.put(FLUORINE, "fluorine");
            this.put(NEON, "neon");
            this.put(SODIUM, "sodium");
            this.put(MAGNESIUM, "magnesium");
            this.put(ALUMINIUM, "aluminium");
            this.put(SILICON, "silicon");
            this.put(PHOSPHORUS, "phosphorus");
            this.put(SULFUR, "sulfur");
            this.put(CHLORINE, "chlorine");
            this.put(ARGON, "argon");
            this.put(POTASSIUM, "potassium");
            this.put(CALCIUM, "calcium");
            this.put(SCANDIUM, "scandium");
            this.put(TITANIUM, "titanium");
            this.put(VANADIUM, "vanadium");
            this.put(CHROMIUM, "chromium");
            this.put(MANGANESE, "manganese");
            this.put(IRON, "iron");
            this.put(COBALT, "cobalt");
            this.put(NICKEL, "nickel");
            this.put(COPPER, "copper");
            this.put(ZINC, "zinc");
            this.put(GALLIUM, "gallium");
            this.put(GERMANIUM, "germanium");
            this.put(ARSENIC, "arsenic");
            this.put(SELENIUM, "selenium");
            this.put(BROMINE, "bromine");
            this.put(KRYPTON, "krypton");
            this.put(RUBIDIUM, "rubidium");
            this.put(STRONTIUM, "strontium");
            this.put(YTTRIUM, "yttrium");
            this.put(ZIRCONIUM, "zirconium");
            this.put(NIOBIUM, "niobium");
            this.put(MOLYBDENUM, "molybdenum");
            this.put(TECHNETIUM, "technetium");
            this.put(RUTHENIUM, "ruthenium");
            this.put(RHODIUM, "rhodium");
            this.put(PALLADIUM, "palladium");
            this.put(SILVER, "silver");
            this.put(CADMIUM, "cadmium");
            this.put(INDIUM, "indium");
            this.put(TIN, "tin");
            this.put(ANTIMONY, "antimony");
            this.put(TELLURIUM, "tellurium");
            this.put(IODINE, "iodine");
            this.put(XENON, "xenon");
            this.put(CESIUM, "cesium");
            this.put(BARIUM, "barium");
            this.put(LANTHANUM, "lanthanum");
            this.put(CERIUM, "cerium");
            this.put(PRASEODYMIUM, "praseodymium");
            this.put(NEODYMIUM, "neodymium");
            this.put(PROMETHIUM, "promethium");
            this.put(SAMARIUM, "samarium");
            this.put(EUROPIUM, "europium");
            this.put(GADOLINIUM, "gadolinium");
            this.put(TERBIUM, "terbium");
            this.put(DYSPROSIUM, "dysprosium");
            this.put(HOLMIUM, "holmium");
            this.put(ERBIUM, "erbium");
            this.put(THULIUM, "thulium");
            this.put(YTTERBIUM, "ytterbium");
            this.put(LUTETIUM, "lutetium");
            this.put(HAFNIUM, "hafnium");
            this.put(TANTALUM, "tantalum");
            this.put(TUNGSTEN, "tungsten");
            this.put(RHENIUM, "rhenium");
            this.put(OSMIUM, "osmium");
            this.put(IRIDIUM, "iridium");
            this.put(PLATINUM, "platinum");
            this.put(GOLD, "gold");
            this.put(MERCURY, "mercury");
            this.put(THALLIUM, "thallium");
            this.put(LEAD, "lead");
            this.put(BISMUTH, "bismuth");
            this.put(POLONIUM, "polonium");
            this.put(ASTATINE, "astatine");
            this.put(RADON, "radon");
            this.put(FRANCIUM, "francium");
            this.put(RADIUM, "radium");
            this.put(ACTINIUM, "actinium");
            this.put(THORIUM, "thorium");
            this.put(PROTACTINIUM, "protactinium");
            this.put(URANIUM, "uranium");
            this.put(NEPTUNIUM, "neptunium");
            this.put(PLUTONIUM, "plutonium");
            this.put(AMERICIUM, "americium");
            this.put(CURIUM, "curium");
            this.put(BERKELIUM, "berkelium");
            this.put(CALIFORNIUM, "californium");
            this.put(EINSTEINIUM, "einsteinium");
            this.put(FERMIUM, "fermium");
            this.put(MENDELEVIUM, "mendelevium");
            this.put(NOBELIUM, "nobelium");
            this.put(LAWRENCIUM, "lawrencium");
            this.put(RUTHERFORDIUM, "rutherfordium");
            this.put(DUBNIUM, "dubnium");
            this.put(SEABORGIUM, "seaborgium");
            this.put(BOHRIUM, "bohrium");
            this.put(HASSIUM, "hassium");
            this.put(MEITNERIUM, "meitnerium");
            this.put(DARMSTADTIUM, "darmstadtium");
            this.put(ROENTGENIUM, "roentgenium");
            this.put(COPERNICIUM, "copernicium");
            this.put(NIHONIUM, "nihonium");
            this.put(FLEROVIUM, "flerovium");
            this.put(MOSCOVIUM, "moscovium");
            this.put(LIVERMORIUM, "livermorium");
            this.put(TENNESSINE, "tennessine");
            this.put(OGANESSON, "oganesson");
            
            this.put(WATER, "water");
        }
    };

    public static String getNameByChemicalFormula(String chemicalFormula)
    {
        if (NAME_TABLE.containsKey(chemicalFormula))
            return NAME_TABLE.get(chemicalFormula);
        else
            throw new Error("Cannot get name for \"" + chemicalFormula + "\"");
    }

    public ChemicalFormula()
    {

    }
}